server:
  address: "http://127.0.0.1:8080"

database:
  address: "127.0.0.1:3306"
  user: "root"
  password: ""
  name: "tester_example_tasks_db"

cases:
  reader:
    file_path: "./cases.json"
    batch_size: 10
  reporter:
    excluded_headers:
      - "Content-Length"
      - "Date"